---

- name: Craete Swarm project path
  file:
    path: "/var/devops/{{ swarm_main_folder }}"
    state: directory

- name: Craete necessary path in server for SwarmTemplate
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ swarm_folders }}"  

- name: Craete necessary path in server for SwarmTemplate
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ swarm_volume_full_paths }}"  

- name: Makefile template
  template:
    src: "{{ swarm_makefile_template }}"
    dest: "{{ swarm_full_path }}/Makefile" 

- name: Config template
  template:
    src: "{{ swarm_services_template }}"
    dest: "{{ swarm_services }}/config.yaml" 

- name: Database template
  template:
    src: "{{ swarm_databases_template }}"
    dest: "{{ swarm_databases }}/postgres.yaml" 

- name: Redis template
  template:
    src: "{{ swarm_redis_template }}"
    dest: "{{ swarm_redis }}/redis.yaml" 


### ONLY TEST PURPOSES, DON'T TRY ON YOURSELF

# - name: Swarm Up
#   shell: make services-up
#   args:
#     chdir: /var/devops/test
#   become: yes
