- name: Install Docker, Docker Compose, and deploy Nginx
  hosts: web_servers
  become: yes

  tasks:
    # Установка зависимостей
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    # Добавление GPG-ключа Docker
    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    # Добавление репозитория Docker
    - name: Add Docker repository
      shell: |
         echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    # Установка Docker и Docker Compose
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    # Убедимся, что Docker работает
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    # Добавление пользователя в группу Docker
    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Копируем docker-compose.yml
    - name: Copy docker-compose.yml
      copy:
        src: ../files/docker-compose.yml
        dest: /{{ ansible_user }}/docker-compose.yml
        mode: '0644'

    # Запускаем Nginx через Docker Compose
    - name: Start Nginx container
      shell: |
        cd /{{ ansible_user }}/ && docker compose up -d
