---
- name: Install Nginx on web servers
  hosts: web_servers  # Указывает на группу хостов
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure nginx is at the latest version
      apt:
        name: postgresql
        state: latest
